# Generated by Django 5.0.4 on 2024-05-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='publication_date',
            field=models.DateField(default=None),
        ),
    ]
