# Generated by Django 5.0.4 on 2024-05-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_category_bookinfo_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
